// Generated by https://quicktype.io

export interface iProductos {
    products: iProduct[];
}

export interface iProduct {
    barcode_number:          string;
    barcode_formats:         string;
    mpn:                     string;
    model:                   string;
    asin:                    string;
    title:                   string;
    category:                string;
    manufacturer:            string;
    brand:                   string;
    contributors:            iContributor[];
    age_group:               string;
    ingredients:             string;
    nutrition_facts:         string;
    energy_efficiency_class: string;
    color:                   string;
    gender:                  string;
    material:                string;
    pattern:                 string;
    format:                  string;
    multipack:               string;
    size:                    string;
    length:                  string;
    width:                   string;
    height:                  string;
    weight:                  string;
    release_date:            string;
    description:             string;
    features:                string[];
    images:                  string[];
    last_update:             string;
    stores:                  iStore[];
    reviews:                 iReview[];
}

export interface iContributor {
    role: string;
    name: string;
}

export interface iReview {
    name:   string;
    rating: string;
    title:  string;
    review: string;
    date:   string;
}

export interface iStore {
    name:            string;
    country:         string;
    currency:        string;
    currency_symbol: string;
    price:           string;
    sale_price:      string;
    tax:             iTax[];
    link:            string;
    item_group_id:   string;
    availability:    string;
    condition:       string;
    shipping:        iShipping[];
    last_update:     string;
}

export interface iShipping {
    country: string;
    region:  string;
    service: string;
    price:   string;
}

export interface iTax {
    country:  string;
    region:   string;
    rate:     string;
    tax_ship: string;
}
